### ISSUE TITLE
# Auth using Firebase Auth

### ISSUE THREAD

**Issue by gbj** [gbj/venite#17]
- [x] Avatar/menu for top-right corner
- [x] Better UI flow (button to close modal, etc.)
- [x] Update user avatar
- [x] Build a better AuthGuard
- [x] Build registration flow into the modal
- [x] Form validation (check username, etc.)
