### ISSUE TITLE
Port Venite liturgies to LDF

### ISSUE THREAD

**Issue by gbj** [gbj/venite#19]
- [ ] Tests for `Prayer` adapters
- [ ] Liturgy `piece` adapter
  - [ ] Tests
- [ ] `Liturgy` adapter
  - [ ] Tests
- [ ] Prayers and Thanksgivings adapter (use Categories to reproduce tree structure)
- [ ] Port into Firestore
