### ISSUE TITLE
Build Permissions/Sharing structures

### ISSUE THREAD

**Issue by gbj** [gbj/venite#21]
- [x] Organizations
  - [x] Model
  - [x] Interface
    - [x] "Find my church" in Register
    - [x] "Create a church" in Register
    - [x] View Organization
    - [x] Add/remove members to/from organization
    - [x] Make members editors
- [x] Firebase permissions
