### ISSUE TITLE
Build Editor engine using Firestore

### ISSUE THREAD

**Issue by gbj** [gbj/venite#22]
- [x] Store DocumentManager class in Firestore
- [x] Join/leave documents
- [x] Update cursors
- [x] Send doc updates
- [x] Debounce ldf-editable-text changes
- [x] Apply doc updates from external users via Automerge
   - [x] Problem is that Automerge docs on different machines have different IDs — to fix, create Automerge doc on first and stash it in the database
   - [x] Use `manager.doc` instead of `this._automergeDoc`
- [x] "Publish" or save doc, i.e., apply all changes to `DocumentManager.doc` and store that in `Document` collection
- [x] Finish JSON1 OT implementation
- [ ] Write tests for OT using Firebase emulators
- [ ] Fix bug when a new change is made before the previous one has been applied
- [x] Tests for OT situations using Firestore security rules
- [ ] Move cursors on changes
- [x] Clean up `DocumentManager` objects in database if there are no users left
- [ ] Security on database -- only allow users to edit own field in users or cursor

**Comment by gbj** [comment]
This is now in a working state as of commit bf42d0493cc6d206edc4d0d0d383512ac8c96cc7, so I'm going to close this issue and create smaller issues for the remaining tasks.
