### ISSUE TITLE
Add Hymn type

### ISSUE THREAD

**Issue by gbj** [gbj/venite#24]
- [ ] LDF
- [ ] Component
  - [ ] label-bar with headings
  - [ ] editable: a button that launches a modal with typeahead index lookup
- [ ] Hymnal indexes into Firebase
- [ ] HymnalService in Angular app
- [ ] Typeahead interface to look up
